### PR TITLE
Added triplets, normalisation, and vector utilities

### PR DESCRIPTION
**Pull request by LowSpecCorgi**
Added:
 - Triplets
 - Vector utilities
 - Integer utility
 - Colour normalisation utlity

### CODE REVIEW

**Comment by isXander** [comment]
You should fix your gpg key...

**Comment by LowSpecCorgi** [comment]
> You should fix your gpg key...

I should, but gpg key doesn't really affect anything.

**Comment by LowSpecCorgi** [comment]
Slight error has been made with the `dotProduct` utility.

Fix will be pushed, and pr'ed if this is accepted

**Comment by LowSpecCorgi** [comment]
More things added, summary:
Added:
 - `.toString()` to pair, triplet, colour and vector types (square brackets indicate a immutable value, normal brackets indicate a mutable value) 
 - `result()` for error handling (example is in `FilesTests`
 - Added basic generic option class
 - Added 2 exceptions
 - Added file extension getter in `Files`
 - Added randomise vector functions
 - Added normalise function for Vec2

Modified:
  - Abstractified the triplets in `Colours`

**Comment by Deftu** [comment]
The `Option` class can be removed in favour of `Provider`

**Comment by LowSpecCorgi** [comment]
> The `Option` class can be removed in favour of `Provider`

Ah all right
I somehow missed it when looking thru the source
Option class has been removed in latest commit

**Comment by Deftu** [comment]
Sorry to ask more, but could you remove the `error_handling` package and move all classes inside there to `exceptions.handling`?

**Comment by LowSpecCorgi** [comment]
> 
> 
> Sorry to ask more, but could you remove the `error_handling` package and move all classes inside there to `exceptions.handling`?

yes :)
will do

**Comment by LowSpecCorgi** [comment]
> 
> 
> Sorry to ask more, but could you remove the `error_handling` package and move all classes inside there to `exceptions.handling`?

Is this oka :P 
6b1c8f37f48bbe9d6fb3ae880662478b653eeda3

**Pull request merged**
